"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Lover_1 = require("../entity/Lover");
var LoverSevervice_1 = require("./LoverSevervice");
var readlineSync = require('readline-sync');
var newObj = new LoverSevervice_1.LoverSevervice();
newObj.add(new Lover_1.Lover('ny1', 'A', 'Aries', 'ha nam', 'game', 5398));
newObj.add(new Lover_1.Lover('ny2', 'B', 'Aries', 'ha nam', 'game', 5398));
newObj.add(new Lover_1.Lover('ny3', 'C', 'Aries', 'ha nam', 'game', 5398));
newObj.add(new Lover_1.Lover('ny4', 'D', 'Aries', 'ha nam', 'game', 5398));
newObj.show();
// newObj.edit('ny1',new Lover('ny5','A','Aries','ha nam','game',5398,));
console.log('Edit NY nao');
var code = readlineSync.question('nhap code ');
var newCode = readlineSync.question('nhap new code ');
var newName = readlineSync.question('nhap new name ');
var newzodiac = readlineSync.question('nhap new zodiac ');
var newAdress = readlineSync.question('nhap new adress ');
var newInterrest = readlineSync.question('nhap new Interrest ');
var newBirthday = readlineSync.question('nhap new Birthday ');
newObj.edit(code, new Lover_1.Lover(newCode, newName, newzodiac, newAdress, newInterrest, newBirthday));
console.log('Delete Lover');
var DeleteLover = readlineSync.question('nhap ny can xao di ');
newObj.delete(DeleteLover);
console.log('Tim em ny nao ngoan di');
var search1 = readlineSync.question('nhap ten em ny can tim di ');
newObj.search(search1);
